name: Push Main to RHEL Server

on:
  push:
    branches:
      - main

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set correct permissions for the repository
        run: |
          sudo chown -R $(whoami):$(whoami) /var/www/html/test
          sudo chmod -R u+rw /var/www/html/test
      - name: Push updates to the RHEL server repository
        run: |
          cd /var/www/html/test
          git fetch origin main
          git reset --hard origin/main
          echo "Repository updated on the server."
